#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset



# N.B. If only .env files supported variable expansion...
export CELERY_BROKER_URL="${REDIS_URL}"

# Skip PostgreSQL check for SQLite
>&2 echo 'Using SQLite database - skipping PostgreSQL check'

exec "$@"
