# Generated by Django 4.2.3 on 2025-10-18 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Organization name", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Organization owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Namespace",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Globally unique namespace name", max_length=100, unique=True)),
                ("description", models.TextField(blank=True, help_text="Namespace description")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="namespaces", to="links.organization"
                    ),
                ),
            ],
            options={
                "verbose_name": "Namespace",
                "verbose_name_plural": "Namespaces",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("original_url", models.URLField(help_text="Original URL to be shortened")),
                (
                    "short_code",
                    models.CharField(help_text="Short code for the URL (unique within namespace)", max_length=50),
                ),
                ("title", models.CharField(blank=True, help_text="Optional title for the short URL", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Optional description for the short URL")),
                ("is_active", models.BooleanField(default=True, help_text="Whether the short URL is active")),
                ("click_count", models.PositiveIntegerField(default=0, help_text="Number of clicks")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_short_urls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="shorturls", to="links.namespace"
                    ),
                ),
            ],
            options={
                "verbose_name": "Short URL",
                "verbose_name_plural": "Short URLs",
                "ordering": ["-created_at"],
                "unique_together": {("namespace", "short_code")},
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("editor", "Editor"), ("viewer", "Viewer")],
                        default="viewer",
                        help_text="User role in the organization",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="links.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Membership",
                "verbose_name_plural": "Organization Memberships",
                "ordering": ["-created_at"],
                "unique_together": {("user", "organization")},
            },
        ),
    ]
