# Generated by Django 4.2.3 on 2025-10-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("urls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorturl",
            name="expiry_date",
            field=models.DateTimeField(blank=True, help_text="Optional expiry date for the short URL", null=True),
        ),
    ]
