# Generated by Django 4.2.3 on 2025-10-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("urls", "0002_shorturl_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="short_code",
            field=models.CharField(
                blank=True, help_text="Short code for the URL (unique within namespace)", max_length=50
            ),
        ),
    ]
