# Generated by Django 4.2.3 on 2025-10-18 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(help_text="6-digit verification code", max_length=6, verbose_name="OTP Code"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created At")),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this OTP has been used for verification",
                        verbose_name="Is Used",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of verification attempts", verbose_name="Attempts"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum number of verification attempts allowed",
                        verbose_name="Max Attempts",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP",
                "verbose_name_plural": "OTPs",
                "ordering": ["-created_at"],
            },
        ),
    ]
